### ISSUE TITLE
publishing views error

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#10]
When running the command:  `php artisan weblog:publish --views`

I receive the following error:
```
 [ErrorException]
 Invalid argument supplied for foreach()
```

However, this command works correctly:
` php artisan vendor:publish --provider="GeneaLabs\LaravelWeblog\Providers\LaravelWeblog" --tag="views"`

**Comment by mikebronner** [comment]
What version of Laravel are you running? (Asking for the other issues as will)

**Comment by drparham** [comment]
Laravel Framework version 5.2.36

**Comment by mikebronner** [comment]
I think this was only an issue with 0.1.0, seems to work fine in master branch. Can you give it a go and let me know (reopen if it still doesn't work for you)?
