### ISSUE TITLE
Published Views not overwritting Package Views

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#11]
Changing some copy on the `index.blade.php` published view does not show in browser. Still loading package views. 

https://github.com/GeneaLabs/laravel-weblog/blob/0.1.0/app/Providers/LaravelWeblog.php#L32-L36

```
 $this->publishes([
            __DIR__.'/../../resources/views' => base_path('resources/views/vendor/genealabs/laravel-weblog/'),
        ], 'views');
  $this->loadViewsFrom(__DIR__.'/../../resources/views', 'genealabs-laravel-weblog');
```

Because you named the views path `genelabs-laravel-weblog`, laravel is actually looking for `resources/views/vendor/genelabs-laravel-weblog`, not `resources/views/vendor/genealabs/laravel-weblog` like you are publishing too.

I think you should change it to this:

```
 $this->publishes([
            __DIR__.'/../../resources/views' => base_path('resources/views/vendor/genealabs-laravel-weblog/'),
        ], 'views');
  $this->loadViewsFrom(__DIR__.'/../../resources/views', 'genealabs-laravel-weblog');
```

This is working correctly for me now.

**Comment by mikebronner** [comment]
Yea, this part is still on my todo list (view overrides)

**Comment by mikebronner** [comment]
Cool :) will check these out tomorrow;  traveling today. Thanks again for all the feedback, it's very much appreciated:)

**Comment by sanjevscet** [comment]
I followed these steps & it is working for me:
  
In service provider, i used this code:

    **public function boot()
    {
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->publishes([
            __DIR__.'/resources/views' => base_path('resources/views/'),
        ]);

        $this->loadViewsFrom(__DIR__.'/resources/views', 'blog');
    }**
then i published my vendor.

In my controller i wrote:
**return view()->first(['blogs', 'blog::blogs']);**

Note: 1) blogs is inside laravel default views folder, while "blog::blogs" is inside our custom package directory.
First, it will check inside Laravel default view directory, if that view is found, its content will be shown otherwise, it will show the package view.

**Comment by mikebronner** [comment]
@sanjevscet Thanks for the feedback .... unfortunately I have not had any time at all to dedicate to this package. I'm not sure if I will be able to resurrect this package. I would love to look at PRs submitted to fix this, if you are able.
