### ISSUE TITLE
Rss Controller Error on empty collection

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#13]
https://github.com/GeneaLabs/laravel-weblog/blob/0.1.0/app/Http/Controllers/Rss.php#L32-L51

Here, we are only pulling posts that have a published_at that isn't null. Unfortunately, for the time being, that creates an empty collection (The add post, isn't populating a published_at date). When running the code block above on an empty collection, it generates an error when trying to convert a null published at to a timestamp.

This creates errors here: 
https://github.com/GeneaLabs/laravel-weblog/blob/0.1.0/app/Http/Controllers/Rss.php#L37

And here:
https://github.com/GeneaLabs/laravel-weblog/blob/0.1.0/app/Http/Controllers/Rss.php#L48

I propose the code block is wrapped in a check if the collection is empty as shown in the below code:

```
        if(!$posts->isEmpty()){
            $channel->title(config('vendor.genealabs.laravel-weblog.title'))
                ->description(config('vendor.genealabs.laravel-weblog.title'))
                ->url(url(config('vendor.genealabs.laravel-weblog.rss-route-name')))
                ->language('en')
                ->copyright(config('vendor.genealabs.laravel-weblog.copyright-notice'))
                ->lastBuildDate($posts->first()->published_at->timestamp)
                ->appendTo($feed);

            foreach ($posts as $post) {
                $item = new Item();

                $item->title($post->title)
                    ->description($post->excerpt)
                    ->contentEncoded($post->content)
                    ->url($post->slug)
                    ->author($post->author->name)
                    ->pubDate($post->published_at->timestamp)
                    ->guid($post->slug, true)
                    ->appendTo($channel);
            }
        }
```

This way if we are indeed returning an empty collection, the code isn't ran to format rss entries, and we return an error free page.

**Comment by mikebronner** [comment]
Fixed
