### ISSUE TITLE
composer.json missing laravel-tagging package

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#4]
Package composer.json should require the tagging package as it's a requirement that isn't specified otherwise.

Add the below to composer.json require sesction:

`"rtconner/laravel-tagging": "~2.1"`

**Comment by mikebronner** [comment]
Ooops, wonder how that slipped through. I probably installed it in the test project, and not in the package itself. :) Thanks! :) Will fix this weekend.
