### ISSUE TITLE
Category Model Post Relationship

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#7]
This is saying Categories have ONE post. Where a Post only belongsTo one Category (based on relationship in the Post model). 

```
public function post() : HasOne
    {
        return $this->hasOne(Post::class);
    }
```

It should be HasMany, since a category will contain many posts, but a post will only belong to a single categroy.

```
public function post() : HasMany
    {
        return $this->hasMany(Post::class);
    }
```

Or do you want to allow a post to belong to more then one category? What do you see as the main difference between a category and a tag?

**Comment by mikebronner** [comment]
This was with the 0.1.0 branch as well, right? All that has been removed in master. PS: use the master branch to play with, has a lot more functionality. The 0.1.0 was a bare minimum and not really usable.
