### ISSUE TITLE
Post Model needs BelongsToMany class

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#8]
`use Illuminate\Database\Eloquent\Relations\BelongsToMany;` 

should be added to use section since this class is being referenced https://github.com/GeneaLabs/laravel-weblog/blob/0.1.0/app/Post.php#L43

**Comment by mikebronner** [comment]
Ah, you were looking at the 0.1.0 branch, not at master. That relationship no longer exists. :) Good eye, though, it was just a placeholder at the time.
