### ISSUE TITLE
routes.php

### ISSUE THREAD

**Issue by drparham** [GeneaLabs/laravel-weblog#9]
So for me, i need to wrap the resource route in a route::group with the middleware web to actually be able to get to the add post page. Otherwise it just keeps taking me to the login page, which once logged in, takes me to the generic redirect path. This solves the issue for me.

https://github.com/GeneaLabs/laravel-weblog/blob/0.1.0/app/Http/routes.php#L11

```
Route::group(['middleware' =>  ['web']], function() {
    Route::resource('posts', Posts::class);
});
```

Instead of 
```
Route::resource('posts', Posts::class);
```

**Comment by mikebronner** [comment]
Can you try this on the master branch (I'm not seeing this issue)? Let me know how that goes.
